In [130]:
from IPython.display import clear_output
import numpy as np
import gym
import random
import time

In [131]:
# Create the env
env = gym.make('FrozenLake-v1', render_mode='ansi',  is_slippery=True)

In [132]:
# Get the size of the action space
action_space_size = env.action_space.n 

# Get the size of the state space
state_space_size = env.observation_space.n

# Initialize the Q-table with zeros 
q_table = np.zeros( (state_space_size, action_space_size) )

In [133]:
# Initializing Q-learning Parameters
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

## Possible actions

0: Move left

1: Move down

2: Move right

3: Move up

# Q-learning algorithm
for episode in range(num_episodes):
    # initialize new episode params

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        # Take new action
        # Update Q-table
        # Set new state
        # Add new reward        

    # Exploration rate decay   
    # Add current episode reward to total rewards list

In [134]:
rewards_all_episodes = []

for episode in range(num_episodes):
    state = env.reset()[0]       # Put the character in the start position
    done = False                 # Flag that the game is reached the end
    rewards_current_episode = 0  # Start the game with no point of reward

    for step in range(max_steps_per_episode):

        # Check wether will explore or exploite 
        exploration_rate_treshold = random.uniform(0, 1)
        if exploration_rate_treshold > exploration_rate: # exploite
            action = np.argmax(q_table[state,:]) # select the action with higher Q-value
        else: # Explore
            action = env.action_space.sample()

        # Taking action
        new_state, reward, done, truncated, info = env.step(action)

        q_table[state, action] =  q_table[state, action] *(1 - learning_rate)  + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        # Change to the new state after the action taken
        state = new_state

        # Add the reward of the current step to the episode
        rewards_current_episode += reward 

        if done == True: 
            break
    
    # Add the reward to the history list
    rewards_all_episodes.append(rewards_current_episode)

    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

# Print the results
print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

print("\n\n********Q-table********\n")
print(q_table)

********Average reward per thousand episodes********

1000 :  0.036000000000000025
2000 :  0.20700000000000016
3000 :  0.4200000000000003
4000 :  0.5650000000000004
5000 :  0.6340000000000005
6000 :  0.6630000000000005
7000 :  0.6920000000000005
8000 :  0.6810000000000005
9000 :  0.6860000000000005
10000 :  0.6630000000000005


********Q-table********

[[0.5712617  0.50521806 0.49041217 0.4878195 ]
 [0.19522335 0.30856165 0.16840755 0.50180022]
 [0.42233355 0.40832941 0.41094513 0.47173372]
 [0.40523119 0.28963761 0.25493098 0.4496651 ]
 [0.591076   0.44916552 0.25790437 0.35649698]
 [0.         0.         0.         0.        ]
 [0.43608351 0.12982108 0.18267638 0.12342126]
 [0.         0.         0.         0.        ]
 [0.30437798 0.38323388 0.52341424 0.61293174]
 [0.54582459 0.65349731 0.54402312 0.22991702]
 [0.62534759 0.43005125 0.36858438 0.3284189 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.43031382 0.62537097 0.75186664

In [136]:
# Vizualisation of the game code
for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, truncated, info = env.step(action)

        if done:
            clear_output(wait=True)
            print(env.render())
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG

****You reached the goal!****
